name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: | 
          docker-compose build
          docker tag abi23_frontend:latest ghcr.io/aifrog/abi23_frontend:latest
          docker tag abi23_backend:latest ghcr.io/aifrog/abi23_backend:latest
          docker push ghcr.io/aifrog/abi23_frontend:latest
          docker push ghcr.io/aifrog/abi23_backend:latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push frontend to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./frontend
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
          


