name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: | 
          docker-compose build
          docker tag abi23_frontend:latest ghcr.io/aifrog/abi23_frontend:latest
          docker tag abi23_backend:latest ghcr.io/aifrog/abi23_backend:latest
          docker push ghcr.io/aifrog/abi23_frontend:latest
          docker push ghcr.io/aifrog/abi23_backend:latest

